version: '2'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=passw0rd
    volumes:
            - data-volume:/var/lib/postgresql/data
  web-init:
      build: ./UPSWeb
      command: bash -c "/code/initserver.sh"
      volumes:
        - ./UPSWeb:/code
      depends_on:
        - db
  web:
      build: ./UPSWeb
      user: nobody
      command:  bash -c "/code/runserver.sh"
      volumes:
        - ./UPSWeb:/code
      expose:
        - "8000"
      depends_on:
        - web-init
  ups:
    build: ./UPS_backend
    user: nobody
    command: bash -c "python3 ./main.py"
    volumes:
      - ./UPS_backend:/code
    expose:
      - "9000"
    ports:
       - "34567:34567"
       - "34568:34568"
    depends_on:
      - db
  nginx:
     image: nginx:latest
     ports:
       - "8000:8000"
     volumes:
       - ./nginx/config:/etc/nginx/conf.d
     depends_on:
       - web
volumes:
   data-volume: