# Generated by Django 4.1.5 on 2023-04-20 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('truck_id', models.AutoField(primary_key=True, serialize=False)),
                ('world_id', models.IntegerField()),
                ('status', models.CharField(choices=[('idle', 'idle'), ('traveling', 'traveling'), ('loading', 'loading'), ('delivering', 'delivering')], max_length=20)),
                ('position_x', models.IntegerField()),
                ('position_y', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UPSAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ups_account_number', models.BigIntegerField()),
                ('world_id', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Package_Info',
            fields=[
                ('package_id', models.IntegerField(primary_key=True, serialize=False)),
                ('world_id', models.IntegerField()),
                ('status', models.CharField(choices=[('packing', 'packing'), ('packed', 'packed'), ('loading', 'loading'), ('loaded', 'loaded'), ('delivering', 'delivering'), ('delivered', 'delivered')], max_length=20)),
                ('destination_x', models.IntegerField()),
                ('destination_y', models.IntegerField()),
                ('warehouse_id', models.IntegerField()),
                ('warehouse_x', models.IntegerField()),
                ('warehouse_y', models.IntegerField()),
                ('truck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_management.truck')),
                ('ups_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_management.upsaccount')),
            ],
        ),
    ]
