# Generated by Django 4.1.5 on 2023-04-23 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_alter_upsaccount_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truck',
            name='world_id',
        ),
        migrations.RemoveField(
            model_name='upsaccount',
            name='ups_account_number',
        ),
        migrations.RemoveField(
            model_name='upsaccount',
            name='world_id',
        ),
        migrations.AddField(
            model_name='package_info',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='package_info',
            name='destination_x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='package_info',
            name='destination_y',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='package_info',
            name='status',
            field=models.CharField(choices=[('prepare_for_delivery', 'prepare_for_delivery'), ('loading', 'loading'), ('delivering', 'delivering'), ('delivered', 'delivered')], max_length=25),
        ),
        migrations.AlterField(
            model_name='package_info',
            name='warehouse_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='package_info',
            name='warehouse_x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='package_info',
            name='warehouse_y',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='status',
            field=models.CharField(choices=[('idle', 'idle'), ('traveling', 'traveling'), ('arrive warehouse', 'arrive warehouse'), ('delivering', 'delivering')], max_length=20),
        ),
    ]
