# Generated by Django 4.1.5 on 2023-04-23 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_remove_truck_world_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package_info',
            name='world_id',
        ),
    ]
