# Generated by Django 4.1.5 on 2023-04-23 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_remove_package_info_world_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='package_info',
            table='packages',
        ),
        migrations.AlterModelTable(
            name='truck',
            table='trucks',
        ),
        migrations.AlterModelTable(
            name='upsaccount',
            table='upsaccount',
        ),
    ]
