# Generated by Django 4.1.5 on 2023-04-24 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_alter_package_info_table_alter_truck_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='warehouse_id',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upsaccount',
            name='ups_account_number',
            field=models.BigIntegerField(default=2),
            preserve_default=False,
        ),
    ]
