# Generated by Django 4.1.5 on 2023-04-24 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0007_rename_ups_account_package_info_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package_info',
            name='user',
        ),
        migrations.AddField(
            model_name='package_info',
            name='user_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
