# Generated by Django 4.1.5 on 2023-04-26 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0008_remove_package_info_user_package_info_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package_info',
            name='status',
            field=models.CharField(choices=[('truck_en_route_to_warehouse', 'truck_en_route_to_warehouse'), ('truck_waiting_for_loading', 'truck_waiting_for_loading'), ('truck_loading', 'truck_loading'), ('truck_loaded', 'truck_loaded'), ('out_for_delivery', 'out_for_delivery'), ('delivered', 'delivered')], max_length=100),
        ),
        migrations.AlterField(
            model_name='truck',
            name='status',
            field=models.CharField(choices=[('idle', 'idle'), ('traveling', 'traveling'), ('arrive_warehouse', 'arrive_warehouse'), ('loading', 'loading'), ('loaded', 'loaded'), ('delivering', 'delivering')], max_length=20),
        ),
    ]
