# Generated by Django 4.2 on 2023-04-29 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0010_alter_package_info_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package_info',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('truck_en_route_to_warehouse', 'truck_en_route_to_warehouse'), ('truck_waiting_for_loading', 'truck_waiting_for_loading'), ('truck_loading', 'truck_loading'), ('truck_loaded', 'truck_loaded'), ('out_for_delivery', 'out_for_delivery'), ('delivered', 'delivered')], max_length=100),
        ),
    ]
