# Generated by Django 4.1.5 on 2023-04-29 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0011_alter_package_info_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='userEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ups_number', models.CharField(max_length=100)),
                ('prod_quality', models.CharField(choices=[('Terrible', 'Terrible'), ('Not great', 'Not great'), ('Mediocre', 'Mediocre'), ('Good', 'Good'), ('Excellent', 'Excellent'), ('Outstanding', 'Outstanding')], max_length=50)),
                ('delivery_quality', models.CharField(choices=[('Terrible', 'Terrible'), ('Not great', 'Not great'), ('Mediocre', 'Mediocre'), ('Good', 'Good'), ('Excellent', 'Excellent'), ('Outstanding', 'Outstanding')], max_length=50)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_management.package_info')),
            ],
            options={
                'db_table': 'evaluations',
            },
        ),
    ]
